name: password_maanger_flutter
description: A new Flutter project with Serverpod.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'
dependencies:
  flutter:
    sdk: flutter
  password_maanger_client:
    path: ../password_maanger_client
  serverpod_flutter: 2.9.1
dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
